name: GitHub Actions Vercel Development Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_DEV }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DEV }}

on:
  push:
    branches:
      - main

jobs:
  Deploy-to-Dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN_DEV }}

      - name: Build Project Artifacts
        run: |
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN_DEV }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN_DEV }}

      # Dummy step to manually break pipeline based on GitHub environment variable
      - name: Fail Pipeline if BREAK_PIPELINE is true
        if: env.BREAK_PIPELINE == 'true'
        run: |
          echo "Manually breaking the pipeline as BREAK_PIPELINE is set to true."
          exit 1
        env:
          BREAK_PIPELINE: ${{ vars.BREAK_PIPELINE }}

  notify-failure:
    runs-on: ubuntu-latest
    needs: [Deploy-to-Dev]
    if: failure()
    steps:
      - name: Send Discord Notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
              "username": "GitHub Actions Alert",
              "content": "🚨 The pipeline failed during the **${{ github.workflow }}** workflow on branch **${{ github.ref_name }}**. Check the logs here: ${{ github.run_url }}"
          }' \
          ${{ secrets.DISCORD_WEBHOOK }}
